# Generated by Django 5.1.5 on 2025-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOs')], default='android', max_length=20)),
                ('form_factor', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet')], default='phone', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
